KEYCLOAK_URL: http://localhost:8000/realms/crm_realm/protocol/openid-connect/certs

server:
  port: 0
spring:
  application:
    name: compose-service

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL}


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      default-zone:
        - http://localhost:8761/eureka/

logging:
  level:
    web: debug
  file:
    name: ./log/compose-service

crm:
  queue:
    baseUrl: http://localhost:80
    customerUrl: /customer-service/api/v1/
    companyUrl: /company-service/api/v1/